FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# MajesticThai

Polls is a simple API allowing consumers to view polls and vote in them.

## Questions Collection [/questions]

### List All Questions [GET]

+ Response 200 (application/json)

        [
            {
                "menu": "Menu",
                "published_at": "2015-08-05T08:40:51.620Z",
                "url": "/dishes",
                "dishes": [
                    {
                        "name": "Sweet & Sour Chicken",
                        "description":,
                        "price": 5.00,
                        "id": 1
                    }, {
                        "name": "Sesame Chicken",
                        "description":,
                        "price": 5.50,
                        "id": 2
                    }, {
                        "name": "Teriyaki Chicken",
                        "description":,
                        "price": 6.00,
                        "id": 3
                    }, {
                        "name": "Fried Rice",
                        "description":,
                        "price": 5.50,
                        "id": 4
                    }
                ]
            }
        ]

### Create a New Question [POST]

You may create your own question using this action. It takes a JSON
object containing a question and a collection of answers in the
form of choices.

+ Request (application/json)

        {
                "menu": "Menu",
                "published_at": "2016-05-01T08:40:51.620Z",
                "url": "/orders",
                "orders": [
                    {
                        "username": "amanda",
                        "ordered-items": [
                            "Sweet & Sour Chicken",
                            "Fried Rice"
                        ],
                        "time": "2016-05-01T08:40:51.620Z",
                        "total": 10.50,
                        "id": 1
                    }, {
                        "username": "hal",
                        "ordered-items": [
                            "Teriyaki Chicken",
                            "Fried Rice"
                        ],
                        "time": "2016-05-01T08:40:51.620Z",
                        "total": 11.50,
                        "id": 2
                    }, {
                        "username": "kay",
                        "ordered-items": [
                            "Sesame Chicken",
                        ],
                        "time": "2016-05-01T08:40:51.620Z",
                        "total": 5.50,
                        "id": 3
                    }
                ]
            }

+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "votes": 0
                    }
                ]
            }